### PR TITLE
Add Node(), Value() and Children() to the Trier interface

### PR DESCRIPTION
**Pull request by dprotaso**
`Node(key string) Trier` will return a subtree of the trie
`Value() interface{}` will return the associated value for the current node
`Children() []Trier` will return the immediate children of the current node

### CODE REVIEW

**Comment by dprotaso** [comment]
@dghubble any thoughts?

**Comment by dghubble** [comment]
What's the justifying use case for providing the internal node? I've found Put/Get to be sufficient.

**Comment by dprotaso** [comment]
For now my use case was - "I want to walk only a subset of the trie"

**Comment by dprotaso** [comment]
For a more concrete use case I'm using this trie lib to index a filesystem

- `Children()` enables querying a list of items at a path
- `Node()` is like `chroot` which makes only a subset of the parent trie visible
- `Value()` & `Children()` combined allow for more control when iterating over nodes in the trie - breadth first vs. the current depth-first

**Comment by dprotaso** [comment]
rebased

**Comment by dprotaso** [comment]
rebased
@dghubble

**Pull request closed without merging**
