### PR TITLE
Add WalkPath function to walk each key/value in path from root to given key

### PR DESCRIPTION
**Pull request by gammazero**
This PR also contains a fix to `PathTrie`:  It was not storing values for empty key "" in the root node, but rather creating a new child of root at "".

### CODE REVIEW

**Comment by dghubble** [comment]
Can you separate the change to PathTrie please?

**Comment by gammazero** [comment]
See PR #13

**Comment by dghubble** [comment]
Can you rebase please?

**Comment by ajgillis** [comment]
Rebased

**Comment by dghubble** [comment]
Thanks

**Pull request merged**
